### PR TITLE
new file format, io-with-bytes

### PR DESCRIPTION
**Pull request by tomhea**
Changed the .fjm file to support versions. after this change, every change will be backwords-compatible.

@lestrozi I need your help - I tried but haven't succeeded in changing quine16.fj to the new version. Basically, the change is just adding 12 zero-bytes after the first 4 bytes (after the magic and the word_size).

### CODE REVIEW

**Comment by lestrozi** [comment]
ooh, this is not too trivial

When you add more data, you'll change the "data_end" position, so "rewinding" it to data-0x10 (which happens in `end_print_code_3`) might involve adding even more instructions in the code - which would in turn add more data (I had to carefully select a where `data-0x10` and `data_end` would be).

On top of that, `end_print_code_4` is in the flip_area, which means bits in it might be flipped and need to be unflipped (this is not difficult though) depending on the data.

Luckily there are 2 instructions left (lines 443-444) which were needed to align data-0x10 and data_end to optimal positions, so they might be enough.

I'll probably need a couple of weeks to give it a try though

**Comment by lestrozi** [comment]
btw, just curious, what is the "flags" field?

**Comment by tomhea** [comment]
Interesting, I can indeed use the flags as i haven't used a non-zero value yet.

These ment to be running-time flags, like changing how to treat IO.

**Comment by tomhea** [comment]
took your idea, version 0 is as it was before, while versions 1+ looks like what I suggested.

**Pull request merged**
